package test.Reservation.ControllerSelenium;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.hamcrest.CoreMatchers;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class TestEmployeeLogin {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {

		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		driver = new ChromeDriver();

		// Wait at least 10 seconds for each page load
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}
	
	public String waitForWindow(int timeout) {
		try {
			Thread.sleep(timeout);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		Set<String> whNow = driver.getWindowHandles();
		Set<String> whThen = (Set<String>) vars.get("window_handles");
		if (whNow.size() > whThen.size()) {
			whNow.removeAll(whThen);
		}
		return whNow.iterator().next();
	}

	@Test
	public void employeeLogin() {
	    driver.get("http://localhost:8080/RestaurantReservation/empLogin");
	    driver.manage().window().setSize(new Dimension(872, 780));
	    driver.findElement(By.id("email")).click();
	    driver.findElement(By.id("email")).sendKeys("vishnu@gmail.com");
	    driver.findElement(By.id("password")).click();
	    driver.findElement(By.id("password")).sendKeys("vishnu");
	    driver.findElement(By.cssSelector(".inlineElement:nth-child(3) .btn")).click();
	    assertThat(driver.findElement(By.cssSelector("h5:nth-child(3)")).getText(), is("Employee Details"));
	    driver.close();
	  }
	}


